### ISSUE TITLE
add automatic deployment

### ISSUE THREAD

**Issue by ahsan8244** [hkumls/hkumls-site#7]

**Comment by eehitray** [comment]
Can work on this within the next 2-3 days if somebody is willing to add a token secret to the repository for the CD to use.

**Comment by ahsan8244** [comment]
> Can work on this within the next 2-3 days if somebody is willing to add a token secret to the repository for the CD to use.

I can help you with that

**Comment by eehitray** [comment]
> > Can work on this within the next 2-3 days if somebody is willing to add a token secret to the repository for the CD to use.
> 
> I can help you with that

Check #29.
